version: "3.9"
services:
  dev_db_nest:
    image: postgres:13
    restart: always
    ports:
      - 5344:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nestNetwork

networks:
  nestNetwork:
